### ISSUE TITLE
[feature] Option to include port number in output

### ISSUE THREAD

**Issue by ThePrez** [juliojsb/jota-cert-checker#13]
I am using the tool to check multiple services running on the same server. It would be great to have an option to include the port number in the provided output. Either by:
- A new column for port number
- Using `sitename:port` in place of `sitename`

**Comment by juliojsb** [comment]
Added **show_port** option for that purpose. Default false, you can set it to true:

![image](https://user-images.githubusercontent.com/12804701/182919230-1a019a28-2e76-42e1-b21a-83a93610f117.png)
