### ISSUE TITLE
how can i transform the output in a html archive

### ISSUE THREAD

**Issue by Dav1XD** [juliojsb/jota-cert-checker#2]
Hi ! 

I wanna know how can i transform the output in a html archive.

Your script help me a lot, but i wanna get the output and transform in a table tag in html.

I don't know if it's possible. But it does not hurt to try :)

**Comment by juliojsb** [comment]
Hi!

The script has been completely reworked and now has the option to generate the output in a HTML file, so it can be an example on how to do it.

Regards,
Jota
