### ISSUE TITLE
Wrong variable in the script

### ISSUE THREAD

**Issue by Xplouder** [juliojsb/jota-cert-checker#3]
Hi,

first `${site}` occurrence should be `${sitename}` instead, otherwise, in some domains, it might produce wrong results depending on how the routing is made.
https://github.com/juliojsb/jota-cert-checker/blob/4324d8ac9165565a3d6d7300a5d279e11b3cdeea/jota-cert-checker.sh#L57

**Comment by juliojsb** [comment]
Hi,

Yes, it should be `${sitename}`, I must have forgot to change it from the very beginning.

Changed in last [commit](https://github.com/juliojsb/jota-cert-checker/commit/74ed11b70bbf5839ab89ee59eabe66859c72d407), thanks!

Regards,
