### ISSUE TITLE
add notification Slack

### ISSUE THREAD

**Issue by andruwa13** [juliojsb/jota-cert-checker#4]
Please add notification to Slack

**Comment by juliojsb** [comment]
Added in last commits. Basically there is a new Python script that converts the HTML file to an image.

You will need to install **imgkit** via pip and **wkhtmltopdf** using your distribution package manager (in RHEL/CentOS you will need to enable EPEL first)

Once installed configure your _slack_token_ variable in the script and you can send the notification to slack:

`./jota-cert-checker.sh -f sitelist -o html -s my_slack_channel`

**Comment by linuxshark** [comment]
Maybe we can completely dockerize the environment and add some standar slack notification, retrieving the slack endpoint as an environment variable.

what do you think?

**Comment by juliojsb** [comment]
This was asked longed time ago... It's an interesting approach, maybe I look to implement the option in the future.
