### ISSUE TITLE
SSL showing expired despite being valid

### ISSUE THREAD

**Issue by lukejtm** [juliojsb/jota-cert-checker#5]
mail.saige.com.au:443 is listed in my report as being expired despite having a valid certificate.

**Comment by juliojsb** [comment]
The script just checks the validity with openssl. In your case it would be:

`echo | openssl s_client -servername mail.saige.com.au -connect mail.saige.com.au:443 2>/dev/null | openssl x509 -noout -enddate 2>/dev/null | cut -d "=" -f2`

Which gives me:

`Oct 20 02:08:14 2021 GMT`


And checking manually:

`echo | openssl s_client -servername mail.saige.com.au -connect mail.saige.com.au:443 2>/dev/null | openssl x509 -text`

Output:

```
Certificate:
    Data:
        Version: 3 (0x2)
        Serial Number:
            ff:5d:5a:d2:ef:ce:44:8d
    Signature Algorithm: sha256WithRSAEncryption
        Issuer: C=US, ST=Arizona, L=Scottsdale, O=GoDaddy.com, Inc., OU=http://certs.godaddy.com/repository/, CN=Go Daddy Secure Certificate Authority - G2
        Validity
            Not Before: Sep 18 02:08:14 2020 GMT
            Not After : Oct 20 02:08:14 2021 GMT
```

Check it manually with openssl to discard any other issue.

Regards,
